#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1

start_instance() {
	config_load "vlmcsd"

	local cfg="$1"
	local enabled auto_activate

	config_get_bool enabled "$cfg" 'enabled' 0
	[ $enabled -gt 0 ] || return 1

	config_get_bool auto_activate "$cfg" auto_activate 0

	if [ "$auto_activate" -eq "1" ];then
		HOSTNAME=$(uci get system.@system[0].hostname)
		host_name=$(awk -F ',' '/^[ \t]*srv-host=_vlmcs\._tcp/{print $2}' /etc/dnsmasq.conf)

		if [ "$HOSTNAME" != "$host_name" ];then
			sed -i '/^[ \t]*srv-host=_vlmcs\._tcp/d' /etc/dnsmasq.conf
			sed -i '$a\srv-host=_vlmcs\._tcp,'"$HOSTNAME"','"1688"',0,100' /etc/dnsmasq.conf
			/etc/init.d/dnsmasq restart >/dev/null 2>&1
		fi
	else
		sed -i '/srv-host=_vlmcs\._tcp,/d' /etc/dnsmasq.conf
		/etc/init.d/dnsmasq restart >/dev/null 2>&1
	fi

	procd_open_instance
	procd_set_param command /usr/bin/vlmcsd
	procd_append_param command -D
	procd_append_param command -i "/etc/vlmcsd/vlmcsd.ini"

	procd_set_param file /etc/vlmcsd/vlmcsd.ini
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn

	procd_close_instance
}

start_service() {
	config_load vlmcsd
	config_foreach start_instance vlmcsd
}

service_triggers() {
	procd_add_reload_trigger "vlmcsd"
}
