#!/bin/sh /etc/rc.common

START=98

USE_PROCD=1

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"
PROG=/usr/bin/qbittorrent-nox

QBT_CONF_FILE=/tmp/qBittorrent/config/qBittorrent.conf

_info() {
	logger -p daemon.info -t "$NAME" "$*"
}

_err() {
	logger -p daemon.err -t "$NAME" "$*"
}

sed_options() {
	local Anchor=$1
	local category="${2// /\\\\}"
	shift; shift;

	if [ -z "$(grep ^\\[$Anchor\\]\$ $QBT_CONF_FILE)" ]; then
		[ -s "$QBT_CONF_FILE" ] && sed -i "\${/./G;s/\$/\n\[$Anchor\]/}"  "$QBT_CONF_FILE" || echo "[$Anchor]" >>"$QBT_CONF_FILE"
	fi

	local o v ol
	for o in "$@"; do
		v="$(eval echo -E "\$$o" | sed 's/[\/\.]/\\&/g')"

		[ -n "$category" ] && ol="$category\\\\$o" || ol="$o"
		ol="${ol//__/\\\\}"

		if [ -n "$v" ]; then
			if [ -z "$(grep ^$ol=.* $QBT_CONF_FILE)" ]; then
				sed -i "/\[$Anchor\]/a $ol=$v" "$QBT_CONF_FILE"
				#sed -i '/\['"$Anchor"'\]/{$ba;h;d};x;/\['"$Anchor"'\]/{x;/./{$bm;H;d};:m;x;:a;s/$/\n'"$ol=$v"'/;x;H};x' "$QBT_CONF_FILE"
			else
				[ "$Overwrite" != "1" ] && [ "$category" != "FileLogger" ] || sed -i "s/$ol=.*/$ol=$v/g" "$QBT_CONF_FILE"
			fi
		else
			[ "$Overwrite" != "1" ] && [ "$category" != "FileLogger" ] || sed -i "/$ol=.*/d" "$QBT_CONF_FILE"
		fi
	done
}

init_instance() {
	[ "$2" = 0 ] || return $2
	[ x"$EnableService" = x1 ] || return 0

	local instance="${NAME}.$1"

	RootProfilePath=$(echo $RootProfilePath | sed 's/\(.*\)\/$/\1/')
	[ -z "$BinaryLocation" ] || PROG="$BinaryLocation"

	local confdir=qBittorrent$([ -z "$ConfigurationName" ] || echo _$ConfigurationName)

	local fullTempPath
	case $TempPath in
	/*|~/*)
		fullTempPath="$TempPath"
	;;
	*)
		fullTempPath="$RootProfilePath/$confdir/$TempPath"
	;;
	esac

	local group=$(id -ng $user)
	for directory in "$RootProfilePath/$confdir" "$RootProfilePath/$confdir/config" "$DefaultSavePath" "$fullTempPath"; do
		if [ -n "$directory" ]; then
			[ -d "$directory" ] || mkdir -m 0755 -p "$directory"
			chmod -R g+w "$directory"
			chown -R "$user:$group" "$directory"
		fi
	done

	# Write to the configuration file.
	QBT_CONF_FILE="$RootProfilePath/$confdir/config/qBittorrent.conf"

	if [ "${#Password}" -eq 32 ]; then
		Password_ha1="@ByteArray($Password)"
	elif [ "${#Password}" -eq 113 ]; then
		Password_PBKDF2="@ByteArray($Password)"
	fi

	if [ -n "$SaveTime" ]; then
		[ -z "$(echo $SaveTime | sed 's/[0-9dmyDMY]//g')" ] || { _err "Error save time setted."; return 1; }

		Age="$(echo $SaveTime | sed 's/[dmyDMY]//g')"
		AgeType="$(echo $SaveTime | sed 's/[0-9]//g' | sed 's/[dD]/0/g' | sed 's/[mM]/1/g' | sed 's/[yY]/2/g')"
	fi

	if [ ! -f "$QBT_CONF_FILE" ]; then
		cat>"$QBT_CONF_FILE"<<-EOF
			[LegalNotice]
			Accepted=true

			[Network]
			Cookies=@Invalid()
		EOF
	fi

	sed_options "BitTorrent" "Session" \
				"AnnounceToAllTiers" "BTProtocol" \
				"SeedChokingAlgorithm" "SlowTorrentsDownloadRate" "SlowTorrentsInactivityTimer" "SlowTorrentsUploadRate"
	sed_options "Preferences" "WebUI" \
				"Address" "Password_ha1" "Password_PBKDF2" "Port" "Username"
	sed_options "Preferences" "Queueing" \
				"IgnoreSlowTorrentsForQueueing" "MaxActiveDownloads" "MaxActiveTorrents" "MaxActiveUploads" \
				"QueueingSystemEnabled"
	sed_options "Preferences" "General" \
				"Locale"
	sed_options "Preferences" "Downloads" \
				"Preallocation" "DefaultSavePath" "TempPathEnabled" "TempPath" "AddExtensionToIncompleteFiles"
	sed_options "Preferences" "Connection" \
				"GlobalDLSpeedLimit" "AlternativeGlobalDLSpeedLimit" "GlobalUPSpeedLimit" "AlternativeGlobalUPSpeedLimit" \
				"PortRangeMin"
	sed_options "Preferences" "Bittorrent" \
				"DHTEnabled" "Encryption" "LSDEnabled" "PeXEnabled"
	sed_options "Preferences" "Advanced" \
				"AnnounceToAllTrackers" "AnonymousModeEnabled" "IgnoreLimitsOnLAN" "IncludeOverheadInLimits" "OutgoingPortsMax" \
				"OutgoingPortsMin"
	sed_options "Application" "FileLogger" \
				"Enabled" "Path" "Backup" "DeleteOld" "MaxSizeBytes" "Age" "AgeType"

	[ "$Overwrite" != "1" ] || sed -i "s/\(MigrationVersion\)=.*/\1=1/g" "$QBT_CONF_FILE"

	procd_open_instance "$instance"
	procd_set_param command "$PROG"
	procd_append_param command --profile="$RootProfilePath"

	[ -z "$ConfigurationName" ] || procd_append_param command --configuration="$ConfigurationName"

	procd_set_param respawn
	procd_set_param user "$user"
	procd_set_param nice "$nice"
	procd_set_param file "$QBT_CONF_FILE"
	procd_set_param term_timeout 60
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}

service_stopped() {
	while running "${NAME}" "${NAME}.main"; do
		sleep 1
	done
}

start_service() {
	uci_load_validate "$NAME" "$NAME" "main" init_instance \
		'EnableService:bool:0' \
		'Overwrite:bool:0' \
		'user:string:root' \
		'nice:range(-20,19):0' \
		'BinaryLocation:string' \
		'RootProfilePath:string:/tmp' \
		'ConfigurationName:string' \
		'DHTEnabled:or("true","false"):true' \
		'Encryption:or("0","1","2"):0' \
		'LSDEnabled:or("true","false"):true' \
		'PeXEnabled:or("true","false"):true' \
		'PortRangeMin:range(1024,65535)' \
		'GlobalDLSpeedLimit:float' \
		'AlternativeGlobalDLSpeedLimit:float' \
		'GlobalUPSpeedLimit:float' \
		'AlternativeGlobalUPSpeedLimit:float' \
		'Preallocation:or("true","false"):false' \
		'DefaultSavePath:string:/tmp/download' \
		'TempPathEnabled:or("true","false"):true' \
		'TempPath:string:temp/' \
		'AddExtensionToIncompleteFiles:or("true","false"):false' \
		'Locale:string:en' \
		'IgnoreSlowTorrentsForQueueing:or("true","false")' \
		'MaxActiveDownloads:integer' \
		'MaxActiveTorrents:integer' \
		'MaxActiveUploads:integer' \
		'QueueingSystemEnabled:or("true","false")' \
		'Address:ipaddr' \
		'Password:string' \
		'Port:port:8080' \
		'Username:string' \
		'AnonymousModeEnabled:or("true","false"):false' \
		'AnnounceToAllTrackers:or("true","false")' \
		'IgnoreLimitsOnLAN:or("true","false"):false' \
		'IncludeOverheadInLimits:or("true","false"):false' \
		'OutgoingPortsMax:port' \
		'OutgoingPortsMin:port' \
		'AnnounceToAllTiers:or("true","false")' \
		'BTProtocol:or("Both","TCP","UTP")' \
		'SeedChokingAlgorithm:or("RoundRobin","FastestUpload","AntiLeech")' \
		'SlowTorrentsDownloadRate:integer' \
		'SlowTorrentsInactivityTimer:integer' \
		'SlowTorrentsUploadRate:integer' \
		'Enabled:or("true","false"):true' \
		'Path:string' \
		'Backup:or("true","false")' \
		'DeleteOld:or("true","false")' \
		'MaxSizeBytes:integer' \
		'SaveTime:string'
}

reload_service() {
	restart
}
