
config qbittorrent 'main'
	option user 'ftp'
	option RootProfilePath '/mnt/sda1/etc'
	option Locale 'zh_CN'
	option BTProtocol 'Both'
	option AddExtensionToIncompleteFiles 'true'
	option Encryption '0'
	option MaxSizeBytes '65536'
	option SaveTime '1m'
	option Preallocation 'true'
	option DefaultSavePath '/mnt/sda1/qBittorrent'
	option TempPath '/mnt/sda1/qBittorrent/temp'
	option SeedChokingAlgorithm 'AntiLeech'
	option MaxActiveDownloads '3'
	option MaxActiveUploads '-1'
	option MaxActiveTorrents '-1'
	option AnnounceToAllTrackers 'true'
	option PortRangeMin '6999'
	option IgnoreSlowTorrentsForQueueing 'true'
	option SlowTorrentsDownloadRate '20'
	option SlowTorrentsUploadRate '20'
	option SlowTorrentsInactivityTimer '60'
	option nice '0'
	option IgnoreLimitsOnLAN 'false'
	option IncludeOverheadInLimits 'true'

