#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/webd

start_instance() {
	local cfg="$1"
	local enabled

	config_get_bool enabled "$cfg" 'enabled' 0
	[ $enabled -gt 0 ] || return 1

	local nofile=$(cat /proc/sys/fs/nr_open)

	procd_open_instance
	procd_set_param limits nofile="${nofile} ${nofile}"
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load 'webd'
	config_foreach start_instance 'base'
}

stop_service() {
	service_stop $PROG
}

service_triggers() {
	procd_add_reload_trigger "webd"
}
