#!/bin/sh


if [ -f "/etc/nginx/luci_nginx.conf" ] && [ -f "/etc/nginx/nginx.conf" ]; then
	if [ ! "$(cat '/etc/nginx/nginx.conf' | grep 'luci*.conf')" ]; then
		if [ -f "/etc/nginx/nginx.conf_old" ]; then
			rm /etc/nginx/nginx.conf
		else
			mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf_old
		fi
		mv /etc/nginx/luci_nginx.conf /etc/nginx/nginx.conf
	else
		rm /etc/nginx/luci_nginx.conf
	fi
fi

if nginx -V 2>&1 | grep -q ubus && [ -f /usr/lib/nginx/modules/ngx_http_ubus_module.so ]; then
        if [ ! -f "/etc/nginx/module.d/luci.module" ]; then
		cat <<EOT >> /etc/nginx/module.d/luci.module
load_module /usr/lib/nginx/modules/ngx_http_brotli_filter_module.so;
load_module /usr/lib/nginx/modules/ngx_http_brotli_static_module.so;
load_module /usr/lib/nginx/modules/ngx_http_dav_ext_module.so;
load_module /usr/lib/nginx/modules/ngx_http_ubus_module.so;
EOT
	fi
fi

if [ -x /etc/init.d/uhttpd ]; then
        /etc/init.d/uhttpd disable
        if [ -n "$(pgrep uhttpd)" ]; then
                /etc/init.d/uhttpd stop
        fi
fi

/etc/init.d/uwsgi enable
if [ -n "$(pgrep uwsgi)" ]; then
        /etc/init.d/uwsgi restart
else
        /etc/init.d/uwsgi start
fi


uci set nginx.@base[0].enabled=1
uci commit nginx
/etc/init.d/nginx restart
exit 0
