log:
  level: error                 # 日志级别
  file: '/var/log/mosdns.log'  # 日志文件路径

plugin:

  ################# 服务插件 ################

  - tag: main_server      # 启动一个服务器，可配置多个
    type: server
    args:
      entry:
        - main_sequence   # 运行主执行序列
      server:
        - protocol: udp
          addr: 127.0.0.1:5335
        - protocol: tcp
          addr: 127.0.0.1:5335
        - protocol: udp
          addr: '[::1]:5335'
        - protocol: tcp
          addr: '[::1]:5335'

  ################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
#        - if:
#            - query_is_ad_domain      # 已知的广告域名
#          exec:
#            - _block_with_nxdomain    # 生成 NXDOMAIN 应答
#            - _end

        - _prefer_ipv4   # 优先 IPv4 地址
#        - _prefer_ipv6   # 优先 IPv6 地址

        - mem_cache                   # 匹配缓存规则

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 不常见的请求类型
          exec:
            - forward_local           # 使用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 使用远程服务器
            - _end

        # 剩下的未知域名用 IP 分流。
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果应答包含本地 IP
          exec:
            - _end                    # 就直接采用结果
        - forward_remote              # 否则去请求远程服务器的结果

  # 缓存规则
  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 10000                     # 内存缓存大小（条）

  - tag: forward_local                # 本地 DNS 服务器
    type: forward
    args:
      upstream:
        - addr: 119.29.29.29
        - addr: 223.5.5.5
        - addr: 114.114.114.114

  - tag: forward_remote               # 远程 DNS 服务器
    type: forward
    args:
      upstream:
        - addr: 'https://dns.cloudflare.com/dns-query'
        - addr: 'https://doh.opendns.com/dns-query'
        - addr: 'https://dns.google/dns-query'

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名
    type: query_matcher
    args:
      domain:
        - 'ext:/usr/share/v2ray/geosite.dat:cn'
        - 'ext:/usr/share/v2ray/geosite.dat:apple-cn'
        - 'ext:/usr/share/v2ray/geosite.dat:google-cn'

  - tag: query_is_non_local_domain    # 匹配非本地域名
    type: query_matcher
    args:
      domain:
        - 'ext:/usr/share/v2ray/geosite.dat:geolocation-!cn'

  - tag: query_is_ad_domain           # 匹配广告域名
    type: query_matcher
    args:
      domain:
        - 'ext:/usr/share/v2ray/geosite.dat:category-ads-all'

  - tag: response_has_local_ip        # 匹配本地 IP
    type: response_matcher
    args:
      ip:
        - 'ext:/usr/share/v2ray/geoip.dat:cn'
